/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AccessControlUnitsRelations} from './AccessControlUnitsRelations';

/**
 * The AccessControlUnits model module.
 * @module model/AccessControlUnits
 * @version 1.0.0
 */
export class AccessControlUnits {
  /**
   * Constructs a new <code>AccessControlUnits</code>.
   * Access control units
   * @alias module:model/AccessControlUnits
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AccessControlUnits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccessControlUnits} obj Optional instance to populate.
   * @return {module:model/AccessControlUnits} The populated <code>AccessControlUnits</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AccessControlUnits();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ruleGroup'))
        obj.ruleGroup = ApiClient.convertToType(data['ruleGroup'], 'String');
      if (data.hasOwnProperty('relations'))
        obj.relations = AccessControlUnitsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
AccessControlUnits.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
AccessControlUnits.prototype.id = undefined;

/**
 * Name
 * @member {String} name
 */
AccessControlUnits.prototype.name = undefined;

/**
 * Rule group path
 * @member {String} ruleGroup
 */
AccessControlUnits.prototype.ruleGroup = undefined;

/**
 * @member {module:model/AccessControlUnitsRelations} relations
 */
AccessControlUnits.prototype.relations = undefined;

