/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AddBasicOwnerInfoServerTask model module.
 * @module model/AddBasicOwnerInfoServerTask
 * @version 1.0.0
 */
export class AddBasicOwnerInfoServerTask {
  /**
   * Constructs a new <code>AddBasicOwnerInfoServerTask</code>.
   * Add basic owner information
   * @alias module:model/AddBasicOwnerInfoServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AddBasicOwnerInfoServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddBasicOwnerInfoServerTask} obj Optional instance to populate.
   * @return {module:model/AddBasicOwnerInfoServerTask} The populated <code>AddBasicOwnerInfoServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddBasicOwnerInfoServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('tagType'))
        obj.tagType = ApiClient.convertToType(data['tagType'], 'String');
      if (data.hasOwnProperty('tagValue'))
        obj.tagValue = ApiClient.convertToType(data['tagValue'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
AddBasicOwnerInfoServerTask.prototype.displayName = undefined;

/**
 * Allowed values for the <code>tagType</code> property.
 * @enum {String}
 * @readonly
 */
AddBasicOwnerInfoServerTask.TagTypeEnum = {
  /**
   * value: "address.Name"
   * @const
   */
  addressName: "address.Name",

  /**
   * value: "address.Address"
   * @const
   */
  addressAddress: "address.Address",

  /**
   * value: "address.State"
   * @const
   */
  addressState: "address.State",

  /**
   * value: "address.Phone"
   * @const
   */
  addressPhone: "address.Phone",

  /**
   * value: "address.Country"
   * @const
   */
  addressCountry: "address.Country",

  /**
   * value: "address.ZipCode"
   * @const
   */
  addressZipCode: "address.ZipCode",

  /**
   * value: "admin.Name"
   * @const
   */
  adminName: "admin.Name",

  /**
   * value: "admin.Address"
   * @const
   */
  adminAddress: "admin.Address",

  /**
   * value: "admin.Phone"
   * @const
   */
  adminPhone: "admin.Phone",

  /**
   * value: "additional.AdditionalInfo"
   * @const
   */
  additionalAdditionalInfo: "additional.AdditionalInfo"
};
/**
 * Select tag type. . Value map to display names:  address.Name=Address - Name   address.Address=Address - Address   address.State=Address - State   address.Phone=Address - Phone   address.Country=Address - Country   address.ZipCode=Address - Zip code   admin.Name=Admin - Name   admin.Address=Admin - Address   admin.Phone=Admin - Phone   additional.AdditionalInfo=Additional - Additional   
 * @member {module:model/AddBasicOwnerInfoServerTask.TagTypeEnum} tagType
 */
AddBasicOwnerInfoServerTask.prototype.tagType = undefined;

/**
 * Value of selected tag. This property can contain any of the BasicInformation fields. The DisplayName contains the readable name, like *Address*, while the Key is prefixed with the group name, e.g. *address.Address* or *admin.Address*. 
 * @member {String} tagValue
 */
AddBasicOwnerInfoServerTask.prototype.tagValue = undefined;

// Implement OneOfinlineResponse20021Result interface:
