/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AlarmDefinitionsRelationsSelf} from './AlarmDefinitionsRelationsSelf';

/**
 * The AlarmDefinitionsRelations model module.
 * @module model/AlarmDefinitionsRelations
 * @version 1.0.0
 */
export class AlarmDefinitionsRelations {
  /**
   * Constructs a new <code>AlarmDefinitionsRelations</code>.
   * @alias module:model/AlarmDefinitionsRelations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AlarmDefinitionsRelations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlarmDefinitionsRelations} obj Optional instance to populate.
   * @return {module:model/AlarmDefinitionsRelations} The populated <code>AlarmDefinitionsRelations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlarmDefinitionsRelations();
      if (data.hasOwnProperty('self'))
        obj.self = AlarmDefinitionsRelationsSelf.constructFromObject(data['self']);
    }
    return obj;
  }
}

/**
 * @member {module:model/AlarmDefinitionsRelationsSelf} self
 */
AlarmDefinitionsRelations.prototype.self = undefined;

