/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ApplyViewItemsXmlServerTask model module.
 * @module model/ApplyViewItemsXmlServerTask
 * @version 1.0.0
 */
export class ApplyViewItemsXmlServerTask {
  /**
   * Constructs a new <code>ApplyViewItemsXmlServerTask</code>.
   * Apply view items XML
   * @alias module:model/ApplyViewItemsXmlServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApplyViewItemsXmlServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplyViewItemsXmlServerTask} obj Optional instance to populate.
   * @return {module:model/ApplyViewItemsXmlServerTask} The populated <code>ApplyViewItemsXmlServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApplyViewItemsXmlServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('viewItemsXml'))
        obj.viewItemsXml = ApiClient.convertToType(data['viewItemsXml'], 'String');
      if (data.hasOwnProperty('beginPosition'))
        obj.beginPosition = ApiClient.convertToType(data['beginPosition'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
ApplyViewItemsXmlServerTask.prototype.displayName = undefined;

/**
 * View items (XML). XML-formatted <viewitems> node containing one or more view items
 * @member {String} viewItemsXml
 */
ApplyViewItemsXmlServerTask.prototype.viewItemsXml = undefined;

/**
 * Insert from position. Index in view to insert from
 * @member {Number} beginPosition
 */
ApplyViewItemsXmlServerTask.prototype.beginPosition = undefined;

// Implement OneOfinlineResponse200115Result interface:
