/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ArchiveSchedules model module.
 * @module model/ArchiveSchedules
 * @version 1.0.0
 */
export class ArchiveSchedules {
  /**
   * Constructs a new <code>ArchiveSchedules</code>.
   * @alias module:model/ArchiveSchedules
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ArchiveSchedules</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArchiveSchedules} obj Optional instance to populate.
   * @return {module:model/ArchiveSchedules} The populated <code>ArchiveSchedules</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArchiveSchedules();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('frequencyType'))
        obj.frequencyType = ApiClient.convertToType(data['frequencyType'], 'String');
      if (data.hasOwnProperty('frequencyRecurrenceFactor'))
        obj.frequencyRecurrenceFactor = ApiClient.convertToType(data['frequencyRecurrenceFactor'], 'Number');
      if (data.hasOwnProperty('frequencyInterval'))
        obj.frequencyInterval = ApiClient.convertToType(data['frequencyInterval'], 'Number');
      if (data.hasOwnProperty('frequencyRelativeInterval'))
        obj.frequencyRelativeInterval = ApiClient.convertToType(data['frequencyRelativeInterval'], 'String');
      if (data.hasOwnProperty('frequencySubDayType'))
        obj.frequencySubDayType = ApiClient.convertToType(data['frequencySubDayType'], 'String');
      if (data.hasOwnProperty('frequencySubDayInterval'))
        obj.frequencySubDayInterval = ApiClient.convertToType(data['frequencySubDayInterval'], 'Number');
      if (data.hasOwnProperty('activeStartTimeOfDay'))
        obj.activeStartTimeOfDay = ApiClient.convertToType(data['activeStartTimeOfDay'], 'Number');
      if (data.hasOwnProperty('activeEndTimeOfDay'))
        obj.activeEndTimeOfDay = ApiClient.convertToType(data['activeEndTimeOfDay'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
ArchiveSchedules.prototype.displayName = undefined;

/**
 * Allowed values for the <code>frequencyType</code> property.
 * @enum {String}
 * @readonly
 */
ArchiveSchedules.FrequencyTypeEnum = {
  /**
   * value: "Unknown"
   * @const
   */
  unknown: "Unknown",

  /**
   * value: "Daily"
   * @const
   */
  daily: "Daily",

  /**
   * value: "Weekly"
   * @const
   */
  weekly: "Weekly",

  /**
   * value: "Monthly"
   * @const
   */
  monthly: "Monthly",

  /**
   * value: "MonthlyRelative"
   * @const
   */
  monthlyRelative: "MonthlyRelative"
};
/**
 * Recurrence pattern. Sets the recurrence pattern to daily, weekly or monthly. Value map to display names:  Unknown=Unknown   Daily=Daily   Weekly=Weekly   Monthly=Monthly   MonthlyRelative=MonthlyRelative   
 * @member {module:model/ArchiveSchedules.FrequencyTypeEnum} frequencyType
 */
ArchiveSchedules.prototype.frequencyType = undefined;

/**
 * Recurrence pattern on weeks/months. Sets the recurrence pattern to daily, weekly or monthly.
 * @member {Number} frequencyRecurrenceFactor
 */
ArchiveSchedules.prototype.frequencyRecurrenceFactor = undefined;

/**
 * Recurrence pattern on days. Defines the ‘Recurrence pattern on days’, which determines how often the archiving is scheduled to run. This property is always interpreted relative to the value of the ‘Recurrence pattern’ property.
 * @member {Number} frequencyInterval
 */
ArchiveSchedules.prototype.frequencyInterval = undefined;

/**
 * Allowed values for the <code>frequencyRelativeInterval</code> property.
 * @enum {String}
 * @readonly
 */
ArchiveSchedules.FrequencyRelativeIntervalEnum = {
  /**
   * value: "First"
   * @const
   */
  first: "First",

  /**
   * value: "Second"
   * @const
   */
  second: "Second",

  /**
   * value: "Third"
   * @const
   */
  third: "Third",

  /**
   * value: "Fourth"
   * @const
   */
  fourth: "Fourth",

  /**
   * value: "Last"
   * @const
   */
  last: "Last"
};
/**
 * Recurrence pattern on relative weekday. Defines the ordinal value of a day relative to the first day of the month, such as first, second or last. Value map to display names:  First=First   Second=Second   Third=Third   Fourth=Fourth   Last=Last   
 * @member {module:model/ArchiveSchedules.FrequencyRelativeIntervalEnum} frequencyRelativeInterval
 */
ArchiveSchedules.prototype.frequencyRelativeInterval = undefined;

/**
 * Allowed values for the <code>frequencySubDayType</code> property.
 * @enum {String}
 * @readonly
 */
ArchiveSchedules.FrequencySubDayTypeEnum = {
  /**
   * value: "Unknown"
   * @const
   */
  unknown: "Unknown",

  /**
   * value: "Once"
   * @const
   */
  once: "Once",

  /**
   * value: "Hour"
   * @const
   */
  hour: "Hour"
};
/**
 * Daily recurrence range type. Defines how often the archiving reoccurs on the same day. Value map to display names:  Unknown=Unknown   Once=Once   Hour=Hour   
 * @member {module:model/ArchiveSchedules.FrequencySubDayTypeEnum} frequencySubDayType
 */
ArchiveSchedules.prototype.frequencySubDayType = undefined;

/**
 * Hourly recurrence range type. Defines the interval between scheduled archiving that run during the day.
 * @member {Number} frequencySubDayInterval
 */
ArchiveSchedules.prototype.frequencySubDayInterval = undefined;

/**
 * Recurrence range start time. Defines the time when the archiving schedule starts for the day in seconds. The value have to be between 0 and 86399.
 * @member {Number} activeStartTimeOfDay
 */
ArchiveSchedules.prototype.activeStartTimeOfDay = undefined;

/**
 * Recurrence range end time. Defines the time when the archiving schedule ends for the day in seconds. The value have to be between 0 and 86399.
 * @member {Number} activeEndTimeOfDay
 */
ArchiveSchedules.prototype.activeEndTimeOfDay = undefined;

