/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ArchiveStoragesRelationsParent} from './ArchiveStoragesRelationsParent';
import {ArchiveStoragesRelationsSelf} from './ArchiveStoragesRelationsSelf';

/**
 * The ArchiveStoragesRelations model module.
 * @module model/ArchiveStoragesRelations
 * @version 1.0.0
 */
export class ArchiveStoragesRelations {
  /**
   * Constructs a new <code>ArchiveStoragesRelations</code>.
   * @alias module:model/ArchiveStoragesRelations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ArchiveStoragesRelations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArchiveStoragesRelations} obj Optional instance to populate.
   * @return {module:model/ArchiveStoragesRelations} The populated <code>ArchiveStoragesRelations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ArchiveStoragesRelations();
      if (data.hasOwnProperty('self'))
        obj.self = ArchiveStoragesRelationsSelf.constructFromObject(data['self']);
      if (data.hasOwnProperty('parent'))
        obj.parent = ArchiveStoragesRelationsParent.constructFromObject(data['parent']);
    }
    return obj;
  }
}

/**
 * @member {module:model/ArchiveStoragesRelationsSelf} self
 */
ArchiveStoragesRelations.prototype.self = undefined;

/**
 * @member {module:model/ArchiveStoragesRelationsParent} parent
 */
ArchiveStoragesRelations.prototype.parent = undefined;

