/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ChangeLicenseRequestBody model module.
 * @module model/ChangeLicenseRequestBody
 * @version 1.0.0
 */
export class ChangeLicenseRequestBody {
  /**
   * Constructs a new <code>ChangeLicenseRequestBody</code>.
   * @alias module:model/ChangeLicenseRequestBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChangeLicenseRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangeLicenseRequestBody} obj Optional instance to populate.
   * @return {module:model/ChangeLicenseRequestBody} The populated <code>ChangeLicenseRequestBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChangeLicenseRequestBody();
      if (data.hasOwnProperty('license'))
        obj.license = ApiClient.convertToType(data['license'], 'String');
    }
    return obj;
  }
}

/**
 * License content base64 encoded
 * @member {String} license
 */
ChangeLicenseRequestBody.prototype.license = undefined;

// Implement LicenseInformationsIdBody interface:
