/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ChangeDeviceRecordingStorageServerTask model module.
 * @module model/ChangeDeviceRecordingStorageServerTask
 * @version 1.0.0
 */
export class ChangeDeviceRecordingStorageServerTask {
  /**
   * Constructs a new <code>ChangeDeviceRecordingStorageServerTask</code>.
   * Change storage for device
   * @alias module:model/ChangeDeviceRecordingStorageServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChangeDeviceRecordingStorageServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangeDeviceRecordingStorageServerTask} obj Optional instance to populate.
   * @return {module:model/ChangeDeviceRecordingStorageServerTask} The populated <code>ChangeDeviceRecordingStorageServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChangeDeviceRecordingStorageServerTask();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('itemSelection'))
        obj.itemSelection = ApiClient.convertToType(data['itemSelection'], 'String');
      if (data.hasOwnProperty('moveData'))
        obj.moveData = ApiClient.convertToType(data['moveData'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} enabled
 */
ChangeDeviceRecordingStorageServerTask.prototype.enabled = undefined;

/**
 * @member {String} displayName
 */
ChangeDeviceRecordingStorageServerTask.prototype.displayName = undefined;

/**
 * Allowed values for the <code>itemSelection</code> property.
 * @enum {String}
 * @readonly
 */
ChangeDeviceRecordingStorageServerTask.ItemSelectionEnum = {
  /**
   * value: "Storage[cb1f599b-325e-4d75-8d11-091747be00d0]"
   * @const
   */
  storageCb1f599b325e4d758d11091747be00d0: "Storage[cb1f599b-325e-4d75-8d11-091747be00d0]"
};
/**
 * Select a storage to move to. .
 * @member {module:model/ChangeDeviceRecordingStorageServerTask.ItemSelectionEnum} itemSelection
 */
ChangeDeviceRecordingStorageServerTask.prototype.itemSelection = undefined;

/**
 * This property is deprecated and will be ignored.
 * @member {Boolean} moveData
 */
ChangeDeviceRecordingStorageServerTask.prototype.moveData = undefined;

// Implement OneOfinlineResponse20029Result interface:
