/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ChildSitesRelations} from './ChildSitesRelations';

/**
 * The ChildSites model module.
 * @module model/ChildSites
 * @version 1.0.0
 */
export class ChildSites {
  /**
   * Constructs a new <code>ChildSites</code>.
   * Child sites
   * @alias module:model/ChildSites
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChildSites</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChildSites} obj Optional instance to populate.
   * @return {module:model/ChildSites} The populated <code>ChildSites</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChildSites();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('lastModified'))
        obj.lastModified = ApiClient.convertToType(data['lastModified'], 'String');
      if (data.hasOwnProperty('connectionState'))
        obj.connectionState = ApiClient.convertToType(data['connectionState'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('serviceAccount'))
        obj.serviceAccount = ApiClient.convertToType(data['serviceAccount'], 'String');
      if (data.hasOwnProperty('synchronizationStatus'))
        obj.synchronizationStatus = ApiClient.convertToType(data['synchronizationStatus'], 'Number');
      if (data.hasOwnProperty('relations'))
        obj.relations = ChildSitesRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
ChildSites.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
ChildSites.prototype.id = undefined;

/**
 * Description
 * @member {String} description
 */
ChildSites.prototype.description = undefined;

/**
 * Last modified
 * @member {String} lastModified
 */
ChildSites.prototype.lastModified = undefined;

/**
 * Site connection state. 
 * @member {String} connectionState
 */
ChildSites.prototype.connectionState = undefined;

/**
 * Product version
 * @member {String} version
 */
ChildSites.prototype.version = undefined;

/**
 * Management server service account
 * @member {String} serviceAccount
 */
ChildSites.prototype.serviceAccount = undefined;

/**
 * Site synchronization status
 * @member {Number} synchronizationStatus
 */
ChildSites.prototype.synchronizationStatus = undefined;

/**
 * @member {module:model/ChildSitesRelations} relations
 */
ChildSites.prototype.relations = undefined;

