/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ClientProfileSetups model module.
 * @module model/ClientProfileSetups
 * @version 1.0.0
 */
export class ClientProfileSetups {
  /**
   * Constructs a new <code>ClientProfileSetups</code>.
   * @alias module:model/ClientProfileSetups
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientProfileSetups</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientProfileSetups} obj Optional instance to populate.
   * @return {module:model/ClientProfileSetups} The populated <code>ClientProfileSetups</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientProfileSetups();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('panesSetupTab'))
        obj.panesSetupTab = ApiClient.convertToType(data['panesSetupTab'], 'String');
      if (data.hasOwnProperty('panesSetupViews'))
        obj.panesSetupViews = ApiClient.convertToType(data['panesSetupViews'], 'String');
      if (data.hasOwnProperty('panesSetupViewsLocked'))
        obj.panesSetupViewsLocked = ApiClient.convertToType(data['panesSetupViewsLocked'], 'Boolean');
      if (data.hasOwnProperty('panesSetupSystemOverview'))
        obj.panesSetupSystemOverview = ApiClient.convertToType(data['panesSetupSystemOverview'], 'String');
      if (data.hasOwnProperty('panesSetupSystemOverviewLocked'))
        obj.panesSetupSystemOverviewLocked = ApiClient.convertToType(data['panesSetupSystemOverviewLocked'], 'Boolean');
      if (data.hasOwnProperty('panesSetupOverlayButtons'))
        obj.panesSetupOverlayButtons = ApiClient.convertToType(data['panesSetupOverlayButtons'], 'String');
      if (data.hasOwnProperty('panesSetupOverlayButtonsLocked'))
        obj.panesSetupOverlayButtonsLocked = ApiClient.convertToType(data['panesSetupOverlayButtonsLocked'], 'Boolean');
      if (data.hasOwnProperty('panesSetupProperties'))
        obj.panesSetupProperties = ApiClient.convertToType(data['panesSetupProperties'], 'String');
      if (data.hasOwnProperty('panesSetupPropertiesLocked'))
        obj.panesSetupPropertiesLocked = ApiClient.convertToType(data['panesSetupPropertiesLocked'], 'Boolean');
      if (data.hasOwnProperty('functionsSetupOverlayButtons'))
        obj.functionsSetupOverlayButtons = ApiClient.convertToType(data['functionsSetupOverlayButtons'], 'String');
      if (data.hasOwnProperty('functionsSetupOverlayButtonsLocked'))
        obj.functionsSetupOverlayButtonsLocked = ApiClient.convertToType(data['functionsSetupOverlayButtonsLocked'], 'Boolean');
      if (data.hasOwnProperty('functionsSetupEnableVideoBufferingOption'))
        obj.functionsSetupEnableVideoBufferingOption = ApiClient.convertToType(data['functionsSetupEnableVideoBufferingOption'], 'String');
      if (data.hasOwnProperty('functionsSetupEnableVideoBufferingOptionLocked'))
        obj.functionsSetupEnableVideoBufferingOptionLocked = ApiClient.convertToType(data['functionsSetupEnableVideoBufferingOptionLocked'], 'Boolean');
      if (data.hasOwnProperty('panesSetupMIPPlugin'))
        obj.panesSetupMIPPlugin = ApiClient.convertToType(data['panesSetupMIPPlugin'], 'String');
      if (data.hasOwnProperty('panesSetupMIPPluginLocked'))
        obj.panesSetupMIPPluginLocked = ApiClient.convertToType(data['panesSetupMIPPluginLocked'], 'Boolean');
      if (data.hasOwnProperty('mapEditMaps'))
        obj.mapEditMaps = ApiClient.convertToType(data['mapEditMaps'], 'String');
      if (data.hasOwnProperty('mapEditGisMap'))
        obj.mapEditGisMap = ApiClient.convertToType(data['mapEditGisMap'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
ClientProfileSetups.prototype.displayName = undefined;

/**
 * Allowed values for the <code>panesSetupTab</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.PanesSetupTabEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Setup mode. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.PanesSetupTabEnum} panesSetupTab
 */
ClientProfileSetups.prototype.panesSetupTab = undefined;

/**
 * Allowed values for the <code>panesSetupViews</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.PanesSetupViewsEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Views pane. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.PanesSetupViewsEnum} panesSetupViews
 */
ClientProfileSetups.prototype.panesSetupViews = undefined;

/**
 * Views pane (Locked)
 * @member {Boolean} panesSetupViewsLocked
 */
ClientProfileSetups.prototype.panesSetupViewsLocked = undefined;

/**
 * Allowed values for the <code>panesSetupSystemOverview</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.PanesSetupSystemOverviewEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * System Overview pane. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.PanesSetupSystemOverviewEnum} panesSetupSystemOverview
 */
ClientProfileSetups.prototype.panesSetupSystemOverview = undefined;

/**
 * System Overview pane (Locked)
 * @member {Boolean} panesSetupSystemOverviewLocked
 */
ClientProfileSetups.prototype.panesSetupSystemOverviewLocked = undefined;

/**
 * Allowed values for the <code>panesSetupOverlayButtons</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.PanesSetupOverlayButtonsEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Overlay Buttons pane. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.PanesSetupOverlayButtonsEnum} panesSetupOverlayButtons
 */
ClientProfileSetups.prototype.panesSetupOverlayButtons = undefined;

/**
 * Overlay Buttons pane (Locked)
 * @member {Boolean} panesSetupOverlayButtonsLocked
 */
ClientProfileSetups.prototype.panesSetupOverlayButtonsLocked = undefined;

/**
 * Allowed values for the <code>panesSetupProperties</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.PanesSetupPropertiesEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Properties pane. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.PanesSetupPropertiesEnum} panesSetupProperties
 */
ClientProfileSetups.prototype.panesSetupProperties = undefined;

/**
 * Properties pane (Locked)
 * @member {Boolean} panesSetupPropertiesLocked
 */
ClientProfileSetups.prototype.panesSetupPropertiesLocked = undefined;

/**
 * Allowed values for the <code>functionsSetupOverlayButtons</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.FunctionsSetupOverlayButtonsEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Edit overlay buttons. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.FunctionsSetupOverlayButtonsEnum} functionsSetupOverlayButtons
 */
ClientProfileSetups.prototype.functionsSetupOverlayButtons = undefined;

/**
 * Edit overlay buttons (Locked)
 * @member {Boolean} functionsSetupOverlayButtonsLocked
 */
ClientProfileSetups.prototype.functionsSetupOverlayButtonsLocked = undefined;

/**
 * Allowed values for the <code>functionsSetupEnableVideoBufferingOption</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.FunctionsSetupEnableVideoBufferingOptionEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Edit live video buffering. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.FunctionsSetupEnableVideoBufferingOptionEnum} functionsSetupEnableVideoBufferingOption
 */
ClientProfileSetups.prototype.functionsSetupEnableVideoBufferingOption = undefined;

/**
 * Edit live video buffering (Locked)
 * @member {Boolean} functionsSetupEnableVideoBufferingOptionLocked
 */
ClientProfileSetups.prototype.functionsSetupEnableVideoBufferingOptionLocked = undefined;

/**
 * Allowed values for the <code>panesSetupMIPPlugin</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.PanesSetupMIPPluginEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * MIP Plug-ins. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.PanesSetupMIPPluginEnum} panesSetupMIPPlugin
 */
ClientProfileSetups.prototype.panesSetupMIPPlugin = undefined;

/**
 * MIP Plug-ins (Locked)
 * @member {Boolean} panesSetupMIPPluginLocked
 */
ClientProfileSetups.prototype.panesSetupMIPPluginLocked = undefined;

/**
 * Allowed values for the <code>mapEditMaps</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.MapEditMapsEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Edit maps. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.MapEditMapsEnum} mapEditMaps
 */
ClientProfileSetups.prototype.mapEditMaps = undefined;

/**
 * Allowed values for the <code>mapEditGisMap</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileSetups.MapEditGisMapEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Edit smart map. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileSetups.MapEditGisMapEnum} mapEditGisMap
 */
ClientProfileSetups.prototype.mapEditGisMap = undefined;

