/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ClientProfileGisMaps model module.
 * @module model/ClientProfileGisMaps
 * @version 1.0.0
 */
export class ClientProfileGisMaps {
  /**
   * Constructs a new <code>ClientProfileGisMaps</code>.
   * @alias module:model/ClientProfileGisMaps
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientProfileGisMaps</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientProfileGisMaps} obj Optional instance to populate.
   * @return {module:model/ClientProfileGisMaps} The populated <code>ClientProfileGisMaps</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientProfileGisMaps();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('gisMapOpenStreetMapGeographicLayer'))
        obj.gisMapOpenStreetMapGeographicLayer = ApiClient.convertToType(data['gisMapOpenStreetMapGeographicLayer'], 'String');
      if (data.hasOwnProperty('gisMapOpenStreetMapGeographicLayerLocked'))
        obj.gisMapOpenStreetMapGeographicLayerLocked = ApiClient.convertToType(data['gisMapOpenStreetMapGeographicLayerLocked'], 'Boolean');
      if (data.hasOwnProperty('gisMapOpenStreetMapAlternativeServer'))
        obj.gisMapOpenStreetMapAlternativeServer = ApiClient.convertToType(data['gisMapOpenStreetMapAlternativeServer'], 'String');
      if (data.hasOwnProperty('gisMapOpenStreetMapAlternativeServerLocked'))
        obj.gisMapOpenStreetMapAlternativeServerLocked = ApiClient.convertToType(data['gisMapOpenStreetMapAlternativeServerLocked'], 'Boolean');
      if (data.hasOwnProperty('gisMapCreateLayerLocation'))
        obj.gisMapCreateLayerLocation = ApiClient.convertToType(data['gisMapCreateLayerLocation'], 'String');
      if (data.hasOwnProperty('gisMapCreateLayerLocationLocked'))
        obj.gisMapCreateLayerLocationLocked = ApiClient.convertToType(data['gisMapCreateLayerLocationLocked'], 'Boolean');
      if (data.hasOwnProperty('gisMapCacheCleanUp'))
        obj.gisMapCacheCleanUp = ApiClient.convertToType(data['gisMapCacheCleanUp'], 'String');
      if (data.hasOwnProperty('gisMapCacheCleanUpLocked'))
        obj.gisMapCacheCleanUpLocked = ApiClient.convertToType(data['gisMapCacheCleanUpLocked'], 'Boolean');
      if (data.hasOwnProperty('gisMapBingMapKey'))
        obj.gisMapBingMapKey = ApiClient.convertToType(data['gisMapBingMapKey'], 'String');
      if (data.hasOwnProperty('gisMapBingMapKeyLocked'))
        obj.gisMapBingMapKeyLocked = ApiClient.convertToType(data['gisMapBingMapKeyLocked'], 'Boolean');
      if (data.hasOwnProperty('gisMapGoogleMapClientId'))
        obj.gisMapGoogleMapClientId = ApiClient.convertToType(data['gisMapGoogleMapClientId'], 'String');
      if (data.hasOwnProperty('gisMapGoogleMapClientIdLocked'))
        obj.gisMapGoogleMapClientIdLocked = ApiClient.convertToType(data['gisMapGoogleMapClientIdLocked'], 'Boolean');
      if (data.hasOwnProperty('gisMapGoogleMapPrivateKey'))
        obj.gisMapGoogleMapPrivateKey = ApiClient.convertToType(data['gisMapGoogleMapPrivateKey'], 'String');
      if (data.hasOwnProperty('gisMapGoogleMapPrivateKeyLocked'))
        obj.gisMapGoogleMapPrivateKeyLocked = ApiClient.convertToType(data['gisMapGoogleMapPrivateKeyLocked'], 'Boolean');
      if (data.hasOwnProperty('gisMapGoogleMapSigningSecret'))
        obj.gisMapGoogleMapSigningSecret = ApiClient.convertToType(data['gisMapGoogleMapSigningSecret'], 'String');
      if (data.hasOwnProperty('gisMapGoogleMapSigningSecretLocked'))
        obj.gisMapGoogleMapSigningSecretLocked = ApiClient.convertToType(data['gisMapGoogleMapSigningSecretLocked'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
ClientProfileGisMaps.prototype.displayName = undefined;

/**
 * Allowed values for the <code>gisMapOpenStreetMapGeographicLayer</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileGisMaps.GisMapOpenStreetMapGeographicLayerEnum = {
  /**
   * value: "Available"
   * @const
   */
  available: "Available",

  /**
   * value: "Unavailable"
   * @const
   */
  unavailable: "Unavailable"
};
/**
 * Milestone Map Service. Value map to display names:  Available=Available   Unavailable=Unavailable   
 * @member {module:model/ClientProfileGisMaps.GisMapOpenStreetMapGeographicLayerEnum} gisMapOpenStreetMapGeographicLayer
 */
ClientProfileGisMaps.prototype.gisMapOpenStreetMapGeographicLayer = undefined;

/**
 * Milestone Map Service (Locked)
 * @member {Boolean} gisMapOpenStreetMapGeographicLayerLocked
 */
ClientProfileGisMaps.prototype.gisMapOpenStreetMapGeographicLayerLocked = undefined;

/**
 * OpenStreetMap server
 * @member {String} gisMapOpenStreetMapAlternativeServer
 */
ClientProfileGisMaps.prototype.gisMapOpenStreetMapAlternativeServer = undefined;

/**
 * OpenStreetMap server (Locked)
 * @member {Boolean} gisMapOpenStreetMapAlternativeServerLocked
 */
ClientProfileGisMaps.prototype.gisMapOpenStreetMapAlternativeServerLocked = undefined;

/**
 * Allowed values for the <code>gisMapCreateLayerLocation</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileGisMaps.GisMapCreateLayerLocationEnum = {
  /**
   * value: "Yes"
   * @const
   */
  yes: "Yes",

  /**
   * value: "No"
   * @const
   */
  no: "No"
};
/**
 * Create location when custom overlay is added. Value map to display names:  Yes=Yes   No=No   
 * @member {module:model/ClientProfileGisMaps.GisMapCreateLayerLocationEnum} gisMapCreateLayerLocation
 */
ClientProfileGisMaps.prototype.gisMapCreateLayerLocation = undefined;

/**
 * Create location when custom overlay is added (Locked)
 * @member {Boolean} gisMapCreateLayerLocationLocked
 */
ClientProfileGisMaps.prototype.gisMapCreateLayerLocationLocked = undefined;

/**
 * Allowed values for the <code>gisMapCacheCleanUp</code> property.
 * @enum {String}
 * @readonly
 */
ClientProfileGisMaps.GisMapCacheCleanUpEnum = {
  /**
   * value: "Never"
   * @const
   */
  never: "Never",

  /**
   * value: "OnScClose"
   * @const
   */
  onScClose: "OnScClose",

  /**
   * value: "OnScClose_IfFileNotUsed"
   * @const
   */
  onScCloseIfFileNotUsed: "OnScClose_IfFileNotUsed"
};
/**
 * Remove cached smart map files. Value map to display names:  Never=Never   OnScClose=On exit   OnScClose_IfFileNotUsed=When not used for 30 days   
 * @member {module:model/ClientProfileGisMaps.GisMapCacheCleanUpEnum} gisMapCacheCleanUp
 */
ClientProfileGisMaps.prototype.gisMapCacheCleanUp = undefined;

/**
 * Remove cached smart map files (Locked)
 * @member {Boolean} gisMapCacheCleanUpLocked
 */
ClientProfileGisMaps.prototype.gisMapCacheCleanUpLocked = undefined;

/**
 * Bing Maps key
 * @member {String} gisMapBingMapKey
 */
ClientProfileGisMaps.prototype.gisMapBingMapKey = undefined;

/**
 * Bing Maps key (Locked)
 * @member {Boolean} gisMapBingMapKeyLocked
 */
ClientProfileGisMaps.prototype.gisMapBingMapKeyLocked = undefined;

/**
 * Client ID for Google Maps
 * @member {String} gisMapGoogleMapClientId
 */
ClientProfileGisMaps.prototype.gisMapGoogleMapClientId = undefined;

/**
 * Client ID for Google Maps (Locked)
 * @member {Boolean} gisMapGoogleMapClientIdLocked
 */
ClientProfileGisMaps.prototype.gisMapGoogleMapClientIdLocked = undefined;

/**
 * Private key for Google Maps
 * @member {String} gisMapGoogleMapPrivateKey
 */
ClientProfileGisMaps.prototype.gisMapGoogleMapPrivateKey = undefined;

/**
 * Private key for Google Maps (Locked)
 * @member {Boolean} gisMapGoogleMapPrivateKeyLocked
 */
ClientProfileGisMaps.prototype.gisMapGoogleMapPrivateKeyLocked = undefined;

/**
 * URL signing secret for Google Maps
 * @member {String} gisMapGoogleMapSigningSecret
 */
ClientProfileGisMaps.prototype.gisMapGoogleMapSigningSecret = undefined;

/**
 * URL signing secret for Google Maps (Locked)
 * @member {Boolean} gisMapGoogleMapSigningSecretLocked
 */
ClientProfileGisMaps.prototype.gisMapGoogleMapSigningSecretLocked = undefined;

