/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ClientSettingsRelations} from './ClientSettingsRelations';
import {PathMicrophones} from './PathMicrophones';

/**
 * The ClientSettings model module.
 * @module model/ClientSettings
 * @version 1.0.0
 */
export class ClientSettings {
  /**
   * Constructs a new <code>ClientSettings</code>.
   * Client settings folder
   * @alias module:model/ClientSettings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientSettings} obj Optional instance to populate.
   * @return {module:model/ClientSettings} The populated <code>ClientSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientSettings();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('related'))
        obj.related = ApiClient.convertToType(data['related'], [PathMicrophones]);
      if (data.hasOwnProperty('shortcut'))
        obj.shortcut = ApiClient.convertToType(data['shortcut'], 'Number');
      if (data.hasOwnProperty('multicastEnabled'))
        obj.multicastEnabled = ApiClient.convertToType(data['multicastEnabled'], 'Boolean');
      if (data.hasOwnProperty('relations'))
        obj.relations = ClientSettingsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
ClientSettings.prototype.displayName = undefined;

/**
 * @member {Array.<module:model/PathMicrophones>} related
 */
ClientSettings.prototype.related = undefined;

/**
 * Shortcut. Shortcut number to be used in clients
 * @member {Number} shortcut
 */
ClientSettings.prototype.shortcut = undefined;

/**
 * Multicast enabled
 * @member {Boolean} multicastEnabled
 */
ClientSettings.prototype.multicastEnabled = undefined;

/**
 * @member {module:model/ClientSettingsRelations} relations
 */
ClientSettings.prototype.relations = undefined;

