/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Error401Details model module.
 * @module model/Error401Details
 * @version 1.0.0
 */
export class Error401Details {
  /**
   * Constructs a new <code>Error401Details</code>.
   * @alias module:model/Error401Details
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Error401Details</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Error401Details} obj Optional instance to populate.
   * @return {module:model/Error401Details} The populated <code>Error401Details</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Error401Details();
      if (data.hasOwnProperty('errorText'))
        obj.errorText = ApiClient.convertToType(data['errorText'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} errorText
 */
Error401Details.prototype.errorText = undefined;

