/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {EventTypesRelationsParent} from './EventTypesRelationsParent';

/**
 * The EventTypeGroupsRelations model module.
 * @module model/EventTypeGroupsRelations
 * @version 1.0.0
 */
export class EventTypeGroupsRelations {
  /**
   * Constructs a new <code>EventTypeGroupsRelations</code>.
   * @alias module:model/EventTypeGroupsRelations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EventTypeGroupsRelations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventTypeGroupsRelations} obj Optional instance to populate.
   * @return {module:model/EventTypeGroupsRelations} The populated <code>EventTypeGroupsRelations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventTypeGroupsRelations();
      if (data.hasOwnProperty('self'))
        obj.self = EventTypesRelationsParent.constructFromObject(data['self']);
    }
    return obj;
  }
}

/**
 * @member {module:model/EventTypesRelationsParent} self
 */
EventTypeGroupsRelations.prototype.self = undefined;

