/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GenericEventDataSourcesRelationsSelf} from './GenericEventDataSourcesRelationsSelf';

/**
 * The GenericEventDataSourcesRelations model module.
 * @module model/GenericEventDataSourcesRelations
 * @version 1.0.0
 */
export class GenericEventDataSourcesRelations {
  /**
   * Constructs a new <code>GenericEventDataSourcesRelations</code>.
   * @alias module:model/GenericEventDataSourcesRelations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GenericEventDataSourcesRelations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GenericEventDataSourcesRelations} obj Optional instance to populate.
   * @return {module:model/GenericEventDataSourcesRelations} The populated <code>GenericEventDataSourcesRelations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GenericEventDataSourcesRelations();
      if (data.hasOwnProperty('self'))
        obj.self = GenericEventDataSourcesRelationsSelf.constructFromObject(data['self']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GenericEventDataSourcesRelationsSelf} self
 */
GenericEventDataSourcesRelations.prototype.self = undefined;

