/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetInternalUnitPathServerTask model module.
 * @module model/GetInternalUnitPathServerTask
 * @version 1.0.0
 */
export class GetInternalUnitPathServerTask {
  /**
   * Constructs a new <code>GetInternalUnitPathServerTask</code>.
   * Get internal unit path
   * @alias module:model/GetInternalUnitPathServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetInternalUnitPathServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetInternalUnitPathServerTask} obj Optional instance to populate.
   * @return {module:model/GetInternalUnitPathServerTask} The populated <code>GetInternalUnitPathServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetInternalUnitPathServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('externalId'))
        obj.externalId = ApiClient.convertToType(data['externalId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
GetInternalUnitPathServerTask.prototype.displayName = undefined;

/**
 * External ID
 * @member {String} externalId
 */
GetInternalUnitPathServerTask.prototype.externalId = undefined;

