/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HardwarePtzChildItem model module.
 * @module model/HardwarePtzChildItem
 * @version 1.0.0
 */
export class HardwarePtzChildItem {
  /**
   * Constructs a new <code>HardwarePtzChildItem</code>.
   * @alias module:model/HardwarePtzChildItem
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HardwarePtzChildItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HardwarePtzChildItem} obj Optional instance to populate.
   * @return {module:model/HardwarePtzChildItem} The populated <code>HardwarePtzChildItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HardwarePtzChildItem();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('ptzUsePtzDeviceID'))
        obj.ptzUsePtzDeviceID = ApiClient.convertToType(data['ptzUsePtzDeviceID'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
HardwarePtzChildItem.prototype.displayName = undefined;

/**
 * PTZ Device ID Required
 * @member {Boolean} ptzUsePtzDeviceID
 */
HardwarePtzChildItem.prototype.ptzUsePtzDeviceID = undefined;

