/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HardwareDriversRelationsSelf} from './HardwareDriversRelationsSelf';
import {HardwareRelationsParent} from './HardwareRelationsParent';

/**
 * The HardwareDriversRelations model module.
 * @module model/HardwareDriversRelations
 * @version 1.0.0
 */
export class HardwareDriversRelations {
  /**
   * Constructs a new <code>HardwareDriversRelations</code>.
   * @alias module:model/HardwareDriversRelations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HardwareDriversRelations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HardwareDriversRelations} obj Optional instance to populate.
   * @return {module:model/HardwareDriversRelations} The populated <code>HardwareDriversRelations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HardwareDriversRelations();
      if (data.hasOwnProperty('self'))
        obj.self = HardwareDriversRelationsSelf.constructFromObject(data['self']);
      if (data.hasOwnProperty('parent'))
        obj.parent = HardwareRelationsParent.constructFromObject(data['parent']);
    }
    return obj;
  }
}

/**
 * @member {module:model/HardwareDriversRelationsSelf} self
 */
HardwareDriversRelations.prototype.self = undefined;

/**
 * @member {module:model/HardwareRelationsParent} parent
 */
HardwareDriversRelations.prototype.parent = undefined;

