/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HardwareDriverSettingsRelations} from './HardwareDriverSettingsRelations';
import {HardwarePtzChildItem} from './HardwarePtzChildItem';

/**
 * The HardwareDriverSettings model module.
 * @module model/HardwareDriverSettings
 * @version 1.0.0
 */
export class HardwareDriverSettings {
  /**
   * Constructs a new <code>HardwareDriverSettings</code>.
   * Hardware settings
   * @alias module:model/HardwareDriverSettings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HardwareDriverSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HardwareDriverSettings} obj Optional instance to populate.
   * @return {module:model/HardwareDriverSettings} The populated <code>HardwareDriverSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HardwareDriverSettings();
      if (data.hasOwnProperty('hardwarePtz'))
        obj.hardwarePtz = HardwarePtzChildItem.constructFromObject(data['hardwarePtz']);
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('relations'))
        obj.relations = HardwareDriverSettingsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {module:model/HardwarePtzChildItem} hardwarePtz
 */
HardwareDriverSettings.prototype.hardwarePtz = undefined;

/**
 * @member {String} displayName
 */
HardwareDriverSettings.prototype.displayName = undefined;

/**
 * @member {module:model/HardwareDriverSettingsRelations} relations
 */
HardwareDriverSettings.prototype.relations = undefined;

