/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PatrollingProfiles} from './PatrollingProfiles';
import {ResourceList} from './ResourceList';
import {TaskList} from './TaskList';

/**
 * The InlineResponse200120 model module.
 * @module model/InlineResponse200120
 * @version 1.0.0
 */
export class InlineResponse200120 {
  /**
   * Constructs a new <code>InlineResponse200120</code>.
   * @alias module:model/InlineResponse200120
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse200120</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200120} obj Optional instance to populate.
   * @return {module:model/InlineResponse200120} The populated <code>InlineResponse200120</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse200120();
      if (data.hasOwnProperty('data'))
        obj.data = PatrollingProfiles.constructFromObject(data['data']);
      if (data.hasOwnProperty('tasks'))
        obj.tasks = ApiClient.convertToType(data['tasks'], [TaskList]);
      if (data.hasOwnProperty('resources'))
        obj.resources = ApiClient.convertToType(data['resources'], [ResourceList]);
    }
    return obj;
  }
}

/**
 * @member {module:model/PatrollingProfiles} data
 */
InlineResponse200120.prototype.data = undefined;

/**
 * @member {Array.<module:model/TaskList>} tasks
 */
InlineResponse200120.prototype.tasks = undefined;

/**
 * @member {Array.<module:model/ResourceList>} resources
 */
InlineResponse200120.prototype.resources = undefined;

