/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MethodIdDeleteRegistrationNumbersServerTask model module.
 * @module model/MethodIdDeleteRegistrationNumbersServerTask
 * @version 1.0.0
 */
export class MethodIdDeleteRegistrationNumbersServerTask {
  /**
   * Constructs a new <code>MethodIdDeleteRegistrationNumbersServerTask</code>.
   * Delete registration numbers
   * @alias module:model/MethodIdDeleteRegistrationNumbersServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MethodIdDeleteRegistrationNumbersServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MethodIdDeleteRegistrationNumbersServerTask} obj Optional instance to populate.
   * @return {module:model/MethodIdDeleteRegistrationNumbersServerTask} The populated <code>MethodIdDeleteRegistrationNumbersServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MethodIdDeleteRegistrationNumbersServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('registrationNumbers'))
        obj.registrationNumbers = ApiClient.convertToType(data['registrationNumbers'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
MethodIdDeleteRegistrationNumbersServerTask.prototype.displayName = undefined;

/**
 * Semicolon separated list of registration numbers
 * @member {String} registrationNumbers
 */
MethodIdDeleteRegistrationNumbersServerTask.prototype.registrationNumbers = undefined;

// Implement OneOfinlineResponse20099Result interface:
