/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MethodIdDeleteRegistrationNumbersRequestBody model module.
 * @module model/MethodIdDeleteRegistrationNumbersRequestBody
 * @version 1.0.0
 */
export class MethodIdDeleteRegistrationNumbersRequestBody {
  /**
   * Constructs a new <code>MethodIdDeleteRegistrationNumbersRequestBody</code>.
   * @alias module:model/MethodIdDeleteRegistrationNumbersRequestBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MethodIdDeleteRegistrationNumbersRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MethodIdDeleteRegistrationNumbersRequestBody} obj Optional instance to populate.
   * @return {module:model/MethodIdDeleteRegistrationNumbersRequestBody} The populated <code>MethodIdDeleteRegistrationNumbersRequestBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MethodIdDeleteRegistrationNumbersRequestBody();
      if (data.hasOwnProperty('registrationNumbers'))
        obj.registrationNumbers = ApiClient.convertToType(data['registrationNumbers'], 'String');
    }
    return obj;
  }
}

/**
 * Semicolon separated list of registration numbers
 * @member {String} registrationNumbers
 */
MethodIdDeleteRegistrationNumbersRequestBody.prototype.registrationNumbers = undefined;

// Implement LprMatchListsIdBody interface:
