/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MethodIdGetCustomFieldsForRegistrationNumberRequestBody model module.
 * @module model/MethodIdGetCustomFieldsForRegistrationNumberRequestBody
 * @version 1.0.0
 */
export class MethodIdGetCustomFieldsForRegistrationNumberRequestBody {
  /**
   * Constructs a new <code>MethodIdGetCustomFieldsForRegistrationNumberRequestBody</code>.
   * @alias module:model/MethodIdGetCustomFieldsForRegistrationNumberRequestBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MethodIdGetCustomFieldsForRegistrationNumberRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MethodIdGetCustomFieldsForRegistrationNumberRequestBody} obj Optional instance to populate.
   * @return {module:model/MethodIdGetCustomFieldsForRegistrationNumberRequestBody} The populated <code>MethodIdGetCustomFieldsForRegistrationNumberRequestBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MethodIdGetCustomFieldsForRegistrationNumberRequestBody();
      if (data.hasOwnProperty('registrationNumber'))
        obj.registrationNumber = ApiClient.convertToType(data['registrationNumber'], 'String');
    }
    return obj;
  }
}

/**
 * Registration number
 * @member {String} registrationNumber
 */
MethodIdGetCustomFieldsForRegistrationNumberRequestBody.prototype.registrationNumber = undefined;

// Implement LprMatchListsIdBody interface:
