/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MethodIdGetCustomFieldsForRegistrationNumberServerTask model module.
 * @module model/MethodIdGetCustomFieldsForRegistrationNumberServerTask
 * @version 1.0.0
 */
export class MethodIdGetCustomFieldsForRegistrationNumberServerTask {
  /**
   * Constructs a new <code>MethodIdGetCustomFieldsForRegistrationNumberServerTask</code>.
   * Get custom fields
   * @alias module:model/MethodIdGetCustomFieldsForRegistrationNumberServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MethodIdGetCustomFieldsForRegistrationNumberServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MethodIdGetCustomFieldsForRegistrationNumberServerTask} obj Optional instance to populate.
   * @return {module:model/MethodIdGetCustomFieldsForRegistrationNumberServerTask} The populated <code>MethodIdGetCustomFieldsForRegistrationNumberServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MethodIdGetCustomFieldsForRegistrationNumberServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('registrationNumber'))
        obj.registrationNumber = ApiClient.convertToType(data['registrationNumber'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
MethodIdGetCustomFieldsForRegistrationNumberServerTask.prototype.displayName = undefined;

/**
 * Registration number
 * @member {String} registrationNumber
 */
MethodIdGetCustomFieldsForRegistrationNumberServerTask.prototype.registrationNumber = undefined;

// Implement OneOfinlineResponse20099Result interface:
