/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MonitorPresetsRelationsSelf} from './MonitorPresetsRelationsSelf';
import {MonitorsRelationsSelf} from './MonitorsRelationsSelf';

/**
 * The MonitorPresetsRelations model module.
 * @module model/MonitorPresetsRelations
 * @version 1.0.0
 */
export class MonitorPresetsRelations {
  /**
   * Constructs a new <code>MonitorPresetsRelations</code>.
   * @alias module:model/MonitorPresetsRelations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MonitorPresetsRelations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MonitorPresetsRelations} obj Optional instance to populate.
   * @return {module:model/MonitorPresetsRelations} The populated <code>MonitorPresetsRelations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MonitorPresetsRelations();
      if (data.hasOwnProperty('self'))
        obj.self = MonitorPresetsRelationsSelf.constructFromObject(data['self']);
      if (data.hasOwnProperty('parent'))
        obj.parent = MonitorsRelationsSelf.constructFromObject(data['parent']);
    }
    return obj;
  }
}

/**
 * @member {module:model/MonitorPresetsRelationsSelf} self
 */
MonitorPresetsRelations.prototype.self = undefined;

/**
 * @member {module:model/MonitorsRelationsSelf} parent
 */
MonitorPresetsRelations.prototype.parent = undefined;

