/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MotionDetectionsRelations} from './MotionDetectionsRelations';

/**
 * The MotionDetections model module.
 * @module model/MotionDetections
 * @version 1.0.0
 */
export class MotionDetections {
  /**
   * Constructs a new <code>MotionDetections</code>.
   * Motion detection
   * @alias module:model/MotionDetections
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MotionDetections</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MotionDetections} obj Optional instance to populate.
   * @return {module:model/MotionDetections} The populated <code>MotionDetections</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MotionDetections();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('manualSensitivityEnabled'))
        obj.manualSensitivityEnabled = ApiClient.convertToType(data['manualSensitivityEnabled'], 'Boolean');
      if (data.hasOwnProperty('manualSensitivity'))
        obj.manualSensitivity = ApiClient.convertToType(data['manualSensitivity'], 'Number');
      if (data.hasOwnProperty('threshold'))
        obj.threshold = ApiClient.convertToType(data['threshold'], 'Number');
      if (data.hasOwnProperty('keyframesOnly'))
        obj.keyframesOnly = ApiClient.convertToType(data['keyframesOnly'], 'Boolean');
      if (data.hasOwnProperty('processTime'))
        obj.processTime = ApiClient.convertToType(data['processTime'], 'String');
      if (data.hasOwnProperty('detectionMethod'))
        obj.detectionMethod = ApiClient.convertToType(data['detectionMethod'], 'String');
      if (data.hasOwnProperty('generateMotionMetadata'))
        obj.generateMotionMetadata = ApiClient.convertToType(data['generateMotionMetadata'], 'Boolean');
      if (data.hasOwnProperty('useExcludeRegions'))
        obj.useExcludeRegions = ApiClient.convertToType(data['useExcludeRegions'], 'Boolean');
      if (data.hasOwnProperty('gridSize'))
        obj.gridSize = ApiClient.convertToType(data['gridSize'], 'String');
      if (data.hasOwnProperty('excludeRegions'))
        obj.excludeRegions = ApiClient.convertToType(data['excludeRegions'], 'String');
      if (data.hasOwnProperty('hardwareAccelerationMode'))
        obj.hardwareAccelerationMode = ApiClient.convertToType(data['hardwareAccelerationMode'], 'String');
      if (data.hasOwnProperty('relations'))
        obj.relations = MotionDetectionsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} enabled
 */
MotionDetections.prototype.enabled = undefined;

/**
 * @member {String} displayName
 */
MotionDetections.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
MotionDetections.prototype.id = undefined;

/**
 * Enable manual motion sensitivity. Disable to let the system dynamically calculate the optimal level
 * @member {Boolean} manualSensitivityEnabled
 */
MotionDetections.prototype.manualSensitivityEnabled = undefined;

/**
 * Motion detection sensitivity. Specify the minimum change required before counting as motion. Value in range 0 - 765
 * @member {Number} manualSensitivity
 */
MotionDetections.prototype.manualSensitivity = undefined;

/**
 * Motion detection threshold. Specify the level of motion required for an event. Value in range 0 - 10000
 * @member {Number} threshold
 */
MotionDetections.prototype.threshold = undefined;

/**
 * Enable motion detection on keyframes only. Optimize the performance on MPEG-4/H.264/H.265 by detecting motion on keyframes only
 * @member {Boolean} keyframesOnly
 */
MotionDetections.prototype.keyframesOnly = undefined;

/**
 * Allowed values for the <code>processTime</code> property.
 * @enum {String}
 * @readonly
 */
MotionDetections.ProcessTimeEnum = {
  /**
   * value: "Ms100"
   * @const
   */
  ms100: "Ms100",

  /**
   * value: "Ms250"
   * @const
   */
  ms250: "Ms250",

  /**
   * value: "Ms500"
   * @const
   */
  ms500: "Ms500",

  /**
   * value: "Ms750"
   * @const
   */
  ms750: "Ms750",

  /**
   * value: "Ms1000"
   * @const
   */
  ms1000: "Ms1000"
};
/**
 * Motion detection check interval. Interval for how often to check for motion. Value map to display names:  Ms100=Ms100   Ms250=Ms250   Ms500=Ms500   Ms750=Ms750   Ms1000=Ms1000   
 * @member {module:model/MotionDetections.ProcessTimeEnum} processTime
 */
MotionDetections.prototype.processTime = undefined;

/**
 * Allowed values for the <code>detectionMethod</code> property.
 * @enum {String}
 * @readonly
 */
MotionDetections.DetectionMethodEnum = {
  /**
   * value: "Normal"
   * @const
   */
  normal: "Normal",

  /**
   * value: "Optimized"
   * @const
   */
  optimized: "Optimized",

  /**
   * value: "Fast"
   * @const
   */
  fast: "Fast"
};
/**
 * Motion detection method. Optimize motion detection by analyzing only a percentage of the image. Value map to display names:  Normal=Normal   Optimized=Optimized   Fast=Fast   
 * @member {module:model/MotionDetections.DetectionMethodEnum} detectionMethod
 */
MotionDetections.prototype.detectionMethod = undefined;

/**
 * Generate motion metadata. Generate motion metadata for smart search function
 * @member {Boolean} generateMotionMetadata
 */
MotionDetections.prototype.generateMotionMetadata = undefined;

/**
 * Use exclude regions. Enable exclude regions in the motion detection
 * @member {Boolean} useExcludeRegions
 */
MotionDetections.prototype.useExcludeRegions = undefined;

/**
 * Allowed values for the <code>gridSize</code> property.
 * @enum {String}
 * @readonly
 */
MotionDetections.GridSizeEnum = {
  /**
   * value: "Grid8X8"
   * @const
   */
  grid8X8: "Grid8X8",

  /**
   * value: "Grid16X16"
   * @const
   */
  grid16X16: "Grid16X16",

  /**
   * value: "Grid32X32"
   * @const
   */
  grid32X32: "Grid32X32",

  /**
   * value: "Grid64X64"
   * @const
   */
  grid64X64: "Grid64X64"
};
/**
 * Grid size. The grid divides the image into selectable regions. If None is selected, exclude regions are disabled. Value map to display names:  Grid8X8=Grid8X8   Grid16X16=Grid16X16   Grid32X32=Grid32X32   Grid64X64=Grid64X64   
 * @member {module:model/MotionDetections.GridSizeEnum} gridSize
 */
MotionDetections.prototype.gridSize = undefined;

/**
 * Exclude regions. Disable motion detection in specific regions. If you use an 8x8 grid, the string should have a length of 64. If you specify 0 or 1, regions are included or excluded respectively from top left region and going left to right.
 * @member {String} excludeRegions
 */
MotionDetections.prototype.excludeRegions = undefined;

/**
 * Allowed values for the <code>hardwareAccelerationMode</code> property.
 * @enum {String}
 * @readonly
 */
MotionDetections.HardwareAccelerationModeEnum = {
  /**
   * value: "Off"
   * @const
   */
  off: "Off",

  /**
   * value: "Automatic"
   * @const
   */
  automatic: "Automatic"
};
/**
 * Hardware acceleration mode. Defines if the motion detection resolution uses automatic or no hardware acceleration. Value map to display names:  Off=Off   Automatic=Automatic   
 * @member {module:model/MotionDetections.HardwareAccelerationModeEnum} hardwareAccelerationMode
 */
MotionDetections.prototype.hardwareAccelerationMode = undefined;

/**
 * @member {module:model/MotionDetectionsRelations} relations
 */
MotionDetections.prototype.relations = undefined;

