/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MoveArchiveStorageServerTask model module.
 * @module model/MoveArchiveStorageServerTask
 * @version 1.0.0
 */
export class MoveArchiveStorageServerTask {
  /**
   * Constructs a new <code>MoveArchiveStorageServerTask</code>.
   * Move archive
   * @alias module:model/MoveArchiveStorageServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MoveArchiveStorageServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MoveArchiveStorageServerTask} obj Optional instance to populate.
   * @return {module:model/MoveArchiveStorageServerTask} The populated <code>MoveArchiveStorageServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MoveArchiveStorageServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('diskPath'))
        obj.diskPath = ApiClient.convertToType(data['diskPath'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
MoveArchiveStorageServerTask.prototype.displayName = undefined;

/**
 * Path. The path to the archive
 * @member {String} diskPath
 */
MoveArchiveStorageServerTask.prototype.diskPath = undefined;

// Implement OneOfinlineResponse20011Result interface:
