/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MoveHardwareRequestBody model module.
 * @module model/MoveHardwareRequestBody
 * @version 1.0.0
 */
export class MoveHardwareRequestBody {
  /**
   * Constructs a new <code>MoveHardwareRequestBody</code>.
   * @alias module:model/MoveHardwareRequestBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MoveHardwareRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MoveHardwareRequestBody} obj Optional instance to populate.
   * @return {module:model/MoveHardwareRequestBody} The populated <code>MoveHardwareRequestBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MoveHardwareRequestBody();
      if (data.hasOwnProperty('destinationRecordingServer'))
        obj.destinationRecordingServer = ApiClient.convertToType(data['destinationRecordingServer'], 'String');
    }
    return obj;
  }
}

/**
 * Destination recording server
 * @member {String} destinationRecordingServer
 */
MoveHardwareRequestBody.prototype.destinationRecordingServer = undefined;

// Implement HardwareIdBody interface:
