/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OutputsRelations} from './OutputsRelations';

/**
 * The Outputs model module.
 * @module model/Outputs
 * @version 1.0.0
 */
export class Outputs {
  /**
   * Constructs a new <code>Outputs</code>.
   * Output
   * @alias module:model/Outputs
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Outputs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Outputs} obj Optional instance to populate.
   * @return {module:model/Outputs} The populated <code>Outputs</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Outputs();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('channel'))
        obj.channel = ApiClient.convertToType(data['channel'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'String');
      if (data.hasOwnProperty('lastModified'))
        obj.lastModified = ApiClient.convertToType(data['lastModified'], 'String');
      if (data.hasOwnProperty('gisPoint'))
        obj.gisPoint = ApiClient.convertToType(data['gisPoint'], 'String');
      if (data.hasOwnProperty('shortName'))
        obj.shortName = ApiClient.convertToType(data['shortName'], 'String');
      if (data.hasOwnProperty('icon'))
        obj.icon = ApiClient.convertToType(data['icon'], 'Number');
      if (data.hasOwnProperty('coverageDirection'))
        obj.coverageDirection = ApiClient.convertToType(data['coverageDirection'], 'Number');
      if (data.hasOwnProperty('coverageDepth'))
        obj.coverageDepth = ApiClient.convertToType(data['coverageDepth'], 'Number');
      if (data.hasOwnProperty('coverageFieldOfView'))
        obj.coverageFieldOfView = ApiClient.convertToType(data['coverageFieldOfView'], 'Number');
      if (data.hasOwnProperty('relations'))
        obj.relations = OutputsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} enabled
 */
Outputs.prototype.enabled = undefined;

/**
 * @member {String} displayName
 */
Outputs.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
Outputs.prototype.id = undefined;

/**
 * Name
 * @member {String} name
 */
Outputs.prototype.name = undefined;

/**
 * Channel
 * @member {Number} channel
 */
Outputs.prototype.channel = undefined;

/**
 * Description
 * @member {String} description
 */
Outputs.prototype.description = undefined;

/**
 * Created date
 * @member {String} createdDate
 */
Outputs.prototype.createdDate = undefined;

/**
 * Last modified
 * @member {String} lastModified
 */
Outputs.prototype.lastModified = undefined;

/**
 * Device position. Device position. Position of device in longitude, latitude and potentially altitude.  The format is \"POINT (LONGITUDE LATITUDE)\" and if you want to clear the coordinates, the value to use is \"POINT EMPTY\".  Examples: \"POINT (55.656932878513 12.3763545558449)\" \"POINT EMPTY\"   Can also include altitude, if so the format is \"POINT (LONGITUDE LATITUDE ALTITUDE)\" 
 * @member {String} gisPoint
 */
Outputs.prototype.gisPoint = undefined;

/**
 * Short name. Used as name in the user interface where appropriate.
 * @member {String} shortName
 */
Outputs.prototype.shortName = undefined;

/**
 * Icon identifier. The relevant device icon to show.
 * @member {Number} icon
 */
Outputs.prototype.icon = undefined;

/**
 * Direction. Indicate the viewing direction of the device.
 * @member {Number} coverageDirection
 */
Outputs.prototype.coverageDirection = undefined;

/**
 * Depth. Indicate the viewing depth of the device.
 * @member {Number} coverageDepth
 */
Outputs.prototype.coverageDepth = undefined;

/**
 * Field of view. Indicate the field of view of the device.
 * @member {Number} coverageFieldOfView
 */
Outputs.prototype.coverageFieldOfView = undefined;

/**
 * @member {module:model/OutputsRelations} relations
 */
Outputs.prototype.relations = undefined;

