/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CamerasRelationsParent} from './CamerasRelationsParent';
import {OutputsRelationsSelf} from './OutputsRelationsSelf';

/**
 * The OutputsRelations model module.
 * @module model/OutputsRelations
 * @version 1.0.0
 */
export class OutputsRelations {
  /**
   * Constructs a new <code>OutputsRelations</code>.
   * @alias module:model/OutputsRelations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OutputsRelations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OutputsRelations} obj Optional instance to populate.
   * @return {module:model/OutputsRelations} The populated <code>OutputsRelations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OutputsRelations();
      if (data.hasOwnProperty('self'))
        obj.self = OutputsRelationsSelf.constructFromObject(data['self']);
      if (data.hasOwnProperty('parent'))
        obj.parent = CamerasRelationsParent.constructFromObject(data['parent']);
    }
    return obj;
  }
}

/**
 * @member {module:model/OutputsRelationsSelf} self
 */
OutputsRelations.prototype.self = undefined;

/**
 * @member {module:model/CamerasRelationsParent} parent
 */
OutputsRelations.prototype.parent = undefined;

