/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OwnerRelations} from './OwnerRelations';

/**
 * The Owner model module.
 * @module model/Owner
 * @version 1.0.0
 */
export class Owner {
  /**
   * Constructs a new <code>Owner</code>.
   * Basic Owner Information
   * @alias module:model/Owner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Owner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Owner} obj Optional instance to populate.
   * @return {module:model/Owner} The populated <code>Owner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Owner();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('relations'))
        obj.relations = OwnerRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
Owner.prototype.displayName = undefined;

/**
 * @member {module:model/OwnerRelations} relations
 */
Owner.prototype.relations = undefined;

