/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PtzPresetsRelations} from './PtzPresetsRelations';

/**
 * The PtzPresets model module.
 * @module model/PtzPresets
 * @version 1.0.0
 */
export class PtzPresets {
  /**
   * Constructs a new <code>PtzPresets</code>.
   * PTZ presets
   * @alias module:model/PtzPresets
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PtzPresets</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PtzPresets} obj Optional instance to populate.
   * @return {module:model/PtzPresets} The populated <code>PtzPresets</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PtzPresets();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('devicePreset'))
        obj.devicePreset = ApiClient.convertToType(data['devicePreset'], 'Boolean');
      if (data.hasOwnProperty('devicePresetInternalId'))
        obj.devicePresetInternalId = ApiClient.convertToType(data['devicePresetInternalId'], 'String');
      if (data.hasOwnProperty('defaultPreset'))
        obj.defaultPreset = ApiClient.convertToType(data['defaultPreset'], 'Boolean');
      if (data.hasOwnProperty('pan'))
        obj.pan = ApiClient.convertToType(data['pan'], 'Number');
      if (data.hasOwnProperty('tilt'))
        obj.tilt = ApiClient.convertToType(data['tilt'], 'Number');
      if (data.hasOwnProperty('zoom'))
        obj.zoom = ApiClient.convertToType(data['zoom'], 'Number');
      if (data.hasOwnProperty('relations'))
        obj.relations = PtzPresetsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
PtzPresets.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
PtzPresets.prototype.id = undefined;

/**
 * Name
 * @member {String} name
 */
PtzPresets.prototype.name = undefined;

/**
 * Description
 * @member {String} description
 */
PtzPresets.prototype.description = undefined;

/**
 * PTZ preset
 * @member {Boolean} devicePreset
 */
PtzPresets.prototype.devicePreset = undefined;

/**
 * Internal ID for PTZ preset
 * @member {String} devicePresetInternalId
 */
PtzPresets.prototype.devicePresetInternalId = undefined;

/**
 * Default PTZ preset
 * @member {Boolean} defaultPreset
 */
PtzPresets.prototype.defaultPreset = undefined;

/**
 * Pan
 * @member {Number} pan
 */
PtzPresets.prototype.pan = undefined;

/**
 * Tilt
 * @member {Number} tilt
 */
PtzPresets.prototype.tilt = undefined;

/**
 * Zoom
 * @member {Number} zoom
 */
PtzPresets.prototype.zoom = undefined;

/**
 * @member {module:model/PtzPresetsRelations} relations
 */
PtzPresets.prototype.relations = undefined;

// Implement IdPtzPresetsBody interface:
