/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PtzSessionTimeouts model module.
 * @module model/PtzSessionTimeouts
 * @version 1.0.0
 */
export class PtzSessionTimeouts {
  /**
   * Constructs a new <code>PtzSessionTimeouts</code>.
   * @alias module:model/PtzSessionTimeouts
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PtzSessionTimeouts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PtzSessionTimeouts} obj Optional instance to populate.
   * @return {module:model/PtzSessionTimeouts} The populated <code>PtzSessionTimeouts</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PtzSessionTimeouts();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('manualPTZTimeout'))
        obj.manualPTZTimeout = ApiClient.convertToType(data['manualPTZTimeout'], 'Number');
      if (data.hasOwnProperty('pausePatrollingTimeout'))
        obj.pausePatrollingTimeout = ApiClient.convertToType(data['pausePatrollingTimeout'], 'Number');
      if (data.hasOwnProperty('reservedPTZTimeout'))
        obj.reservedPTZTimeout = ApiClient.convertToType(data['reservedPTZTimeout'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
PtzSessionTimeouts.prototype.displayName = undefined;

/**
 * Manual PTZ timeout. Stored in seconds. A value of -1 for disabled. Value need to be in hours: e.g. multiple of 3600, or in minutes: multiple of 60, or in seconds: with max value of 999
 * @member {Number} manualPTZTimeout
 */
PtzSessionTimeouts.prototype.manualPTZTimeout = undefined;

/**
 * Pause patrolling timeout. Stored in seconds. A value of -1 for disabled. Value need to be in hours: e.g. multiple of 3600, or in minutes: multiple of 60, or in seconds: with max value of 999
 * @member {Number} pausePatrollingTimeout
 */
PtzSessionTimeouts.prototype.pausePatrollingTimeout = undefined;

/**
 * Reserved PTZ timeout. Stored in seconds. A value of -1 for disabled. Value need to be in hours: e.g. multiple of 3600, or in minutes: multiple of 60, or in seconds: with max value of 999
 * @member {Number} reservedPTZTimeout
 */
PtzSessionTimeouts.prototype.reservedPTZTimeout = undefined;

