/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {RecordingServerFailoversRelations} from './RecordingServerFailoversRelations';

/**
 * The RecordingServerFailovers model module.
 * @module model/RecordingServerFailovers
 * @version 1.0.0
 */
export class RecordingServerFailovers {
  /**
   * Constructs a new <code>RecordingServerFailovers</code>.
   * Failover settings
   * @alias module:model/RecordingServerFailovers
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordingServerFailovers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordingServerFailovers} obj Optional instance to populate.
   * @return {module:model/RecordingServerFailovers} The populated <code>RecordingServerFailovers</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordingServerFailovers();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('primaryFailoverGroup'))
        obj.primaryFailoverGroup = ApiClient.convertToType(data['primaryFailoverGroup'], 'String');
      if (data.hasOwnProperty('secondaryFailoverGroup'))
        obj.secondaryFailoverGroup = ApiClient.convertToType(data['secondaryFailoverGroup'], 'String');
      if (data.hasOwnProperty('hotStandby'))
        obj.hotStandby = ApiClient.convertToType(data['hotStandby'], 'String');
      if (data.hasOwnProperty('failoverPort'))
        obj.failoverPort = ApiClient.convertToType(data['failoverPort'], 'Number');
      if (data.hasOwnProperty('relations'))
        obj.relations = RecordingServerFailoversRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
RecordingServerFailovers.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
RecordingServerFailovers.prototype.id = undefined;

/**
 * Allowed values for the <code>primaryFailoverGroup</code> property.
 * @enum {String}
 * @readonly
 */
RecordingServerFailovers.PrimaryFailoverGroupEnum = {
  /**
   * value: "FailoverGroup[00000000-0000-0000-0000-000000000000]"
   * @const
   */
  _00000000000000000000000000000000: "FailoverGroup[00000000-0000-0000-0000-000000000000]",

  /**
   * value: "FailoverGroup[27D6C895-6C73-4192-B58A-6E6055FD9353]"
   * @const
   */
  _27D6C8956C734192B58A6E6055FD9353: "FailoverGroup[27D6C895-6C73-4192-B58A-6E6055FD9353]"
};
/**
 * Primary failover group. . Value map to display names:  FailoverGroup[00000000-0000-0000-0000-000000000000]=Not used   FailoverGroup[27D6C895-6C73-4192-B58A-6E6055FD9353]=MyFailoverGroup   
 * @member {module:model/RecordingServerFailovers.PrimaryFailoverGroupEnum} primaryFailoverGroup
 */
RecordingServerFailovers.prototype.primaryFailoverGroup = undefined;

/**
 * Allowed values for the <code>secondaryFailoverGroup</code> property.
 * @enum {String}
 * @readonly
 */
RecordingServerFailovers.SecondaryFailoverGroupEnum = {
  /**
   * value: "FailoverGroup[00000000-0000-0000-0000-000000000000]"
   * @const
   */
  _00000000000000000000000000000000: "FailoverGroup[00000000-0000-0000-0000-000000000000]",

  /**
   * value: "FailoverGroup[27D6C895-6C73-4192-B58A-6E6055FD9353]"
   * @const
   */
  _27D6C8956C734192B58A6E6055FD9353: "FailoverGroup[27D6C895-6C73-4192-B58A-6E6055FD9353]"
};
/**
 * Secondary failover group. . Value map to display names:  FailoverGroup[00000000-0000-0000-0000-000000000000]=Not used   FailoverGroup[27D6C895-6C73-4192-B58A-6E6055FD9353]=MyFailoverGroup   
 * @member {module:model/RecordingServerFailovers.SecondaryFailoverGroupEnum} secondaryFailoverGroup
 */
RecordingServerFailovers.prototype.secondaryFailoverGroup = undefined;

/**
 * Allowed values for the <code>hotStandby</code> property.
 * @enum {String}
 * @readonly
 */
RecordingServerFailovers.HotStandbyEnum = {
  /**
   * value: "FailoverRecorder[936631D8-CD32-408E-A876-C8FE7A7C67EA]"
   * @const
   */
  failoverRecorder936631D8CD32408EA876C8FE7A7C67EA: "FailoverRecorder[936631D8-CD32-408E-A876-C8FE7A7C67EA]"
};
/**
 * Hot standby. . Value map to display names:  FailoverRecorder[936631D8-CD32-408E-A876-C8FE7A7C67EA]=rootLevelFailover   
 * @member {module:model/RecordingServerFailovers.HotStandbyEnum} hotStandby
 */
RecordingServerFailovers.prototype.hotStandby = undefined;

/**
 * Failover port
 * @member {Number} failoverPort
 */
RecordingServerFailovers.prototype.failoverPort = undefined;

/**
 * @member {module:model/RecordingServerFailoversRelations} relations
 */
RecordingServerFailovers.prototype.relations = undefined;

