/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RemoveCamerasServerTask model module.
 * @module model/RemoveCamerasServerTask
 * @version 1.0.0
 */
export class RemoveCamerasServerTask {
  /**
   * Constructs a new <code>RemoveCamerasServerTask</code>.
   * Remove cameras
   * @alias module:model/RemoveCamerasServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RemoveCamerasServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RemoveCamerasServerTask} obj Optional instance to populate.
   * @return {module:model/RemoveCamerasServerTask} The populated <code>RemoveCamerasServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RemoveCamerasServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('cameraPaths'))
        obj.cameraPaths = ApiClient.convertToType(data['cameraPaths'], 'String');
      if (data.hasOwnProperty('cameraGroupPaths'))
        obj.cameraGroupPaths = ApiClient.convertToType(data['cameraGroupPaths'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
RemoveCamerasServerTask.prototype.displayName = undefined;

/**
 * Camera paths. Paths of cameras to insert in view
 * @member {String} cameraPaths
 */
RemoveCamerasServerTask.prototype.cameraPaths = undefined;

/**
 * Camera group paths. Paths of camera groups to insert in view
 * @member {String} cameraGroupPaths
 */
RemoveCamerasServerTask.prototype.cameraGroupPaths = undefined;

// Implement OneOfinlineResponse200115Result interface:
