/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RemoveBasicOwnerInfoServerTask model module.
 * @module model/RemoveBasicOwnerInfoServerTask
 * @version 1.0.0
 */
export class RemoveBasicOwnerInfoServerTask {
  /**
   * Constructs a new <code>RemoveBasicOwnerInfoServerTask</code>.
   * Remove basic owner tag
   * @alias module:model/RemoveBasicOwnerInfoServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RemoveBasicOwnerInfoServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RemoveBasicOwnerInfoServerTask} obj Optional instance to populate.
   * @return {module:model/RemoveBasicOwnerInfoServerTask} The populated <code>RemoveBasicOwnerInfoServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RemoveBasicOwnerInfoServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('itemSelection'))
        obj.itemSelection = ApiClient.convertToType(data['itemSelection'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
RemoveBasicOwnerInfoServerTask.prototype.displayName = undefined;

/**
 * Allowed values for the <code>itemSelection</code> property.
 * @enum {String}
 * @readonly
 */
RemoveBasicOwnerInfoServerTask.ItemSelectionEnum = {
  /**
   * value: "d098269a-b5d0-491a-9710-f1be52125e4c"
   * @const
   */
  d098269aB5d0491a9710F1be52125e4c: "d098269a-b5d0-491a-9710-f1be52125e4c",

  /**
   * value: "01680499-d09c-4a18-8ebb-d48656431d3c"
   * @const
   */
  _01680499D09c4a188ebbD48656431d3c: "01680499-d09c-4a18-8ebb-d48656431d3c",

  /**
   * value: "9262a2e3-5f84-403e-b433-dbd3751602bb"
   * @const
   */
  _9262a2e35f84403eB433Dbd3751602bb: "9262a2e3-5f84-403e-b433-dbd3751602bb",

  /**
   * value: "92f6bab2-5c06-405d-b066-3cb1b0ae1a49"
   * @const
   */
  _92f6bab25c06405dB0663cb1b0ae1a49: "92f6bab2-5c06-405d-b066-3cb1b0ae1a49",

  /**
   * value: "9cbb038a-d509-4706-936e-69079ab13617"
   * @const
   */
  _9cbb038aD5094706936e69079ab13617: "9cbb038a-d509-4706-936e-69079ab13617",

  /**
   * value: "076d3352-24b5-4ef0-8edc-3d2c62768ff8"
   * @const
   */
  _076d335224b54ef08edc3d2c62768ff8: "076d3352-24b5-4ef0-8edc-3d2c62768ff8",

  /**
   * value: "bc100d31-3ab5-45ff-b6bd-5012898e9987"
   * @const
   */
  bc100d313ab545ffB6bd5012898e9987: "bc100d31-3ab5-45ff-b6bd-5012898e9987",

  /**
   * value: "68fe7a23-6a9f-4043-954d-4d09b5710c88"
   * @const
   */
  _68fe7a236a9f4043954d4d09b5710c88: "68fe7a23-6a9f-4043-954d-4d09b5710c88",

  /**
   * value: "9970e44d-77e7-4d2b-91a0-ed9aaf114667"
   * @const
   */
  _9970e44d77e74d2b91a0Ed9aaf114667: "9970e44d-77e7-4d2b-91a0-ed9aaf114667",

  /**
   * value: "e5ac1433-8e75-4f45-adda-280d2cd01af6"
   * @const
   */
  e5ac14338e754f45Adda280d2cd01af6: "e5ac1433-8e75-4f45-adda-280d2cd01af6"
};
/**
 * Select tag to remove. .
 * @member {module:model/RemoveBasicOwnerInfoServerTask.ItemSelectionEnum} itemSelection
 */
RemoveBasicOwnerInfoServerTask.prototype.itemSelection = undefined;

// Implement OneOfinlineResponse20021Result interface:
