/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RemoveBasicOwnerInfoRequestBody model module.
 * @module model/RemoveBasicOwnerInfoRequestBody
 * @version 1.0.0
 */
export class RemoveBasicOwnerInfoRequestBody {
  /**
   * Constructs a new <code>RemoveBasicOwnerInfoRequestBody</code>.
   * @alias module:model/RemoveBasicOwnerInfoRequestBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RemoveBasicOwnerInfoRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RemoveBasicOwnerInfoRequestBody} obj Optional instance to populate.
   * @return {module:model/RemoveBasicOwnerInfoRequestBody} The populated <code>RemoveBasicOwnerInfoRequestBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RemoveBasicOwnerInfoRequestBody();
      if (data.hasOwnProperty('itemSelection'))
        obj.itemSelection = ApiClient.convertToType(data['itemSelection'], 'String');
    }
    return obj;
  }
}

/**
 * Select tag to remove
 * @member {String} itemSelection
 */
RemoveBasicOwnerInfoRequestBody.prototype.itemSelection = undefined;

// Implement OwnerIdBody interface:
