/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RetrieveEdgeStorageServerTask model module.
 * @module model/RetrieveEdgeStorageServerTask
 * @version 1.0.0
 */
export class RetrieveEdgeStorageServerTask {
  /**
   * Constructs a new <code>RetrieveEdgeStorageServerTask</code>.
   * Retrieve recordings from edge storage
   * @alias module:model/RetrieveEdgeStorageServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RetrieveEdgeStorageServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RetrieveEdgeStorageServerTask} obj Optional instance to populate.
   * @return {module:model/RetrieveEdgeStorageServerTask} The populated <code>RetrieveEdgeStorageServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RetrieveEdgeStorageServerTask();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('startTime'))
        obj.startTime = ApiClient.convertToType(data['startTime'], 'String');
      if (data.hasOwnProperty('endTime'))
        obj.endTime = ApiClient.convertToType(data['endTime'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} enabled
 */
RetrieveEdgeStorageServerTask.prototype.enabled = undefined;

/**
 * @member {String} displayName
 */
RetrieveEdgeStorageServerTask.prototype.displayName = undefined;

/**
 * Start time
 * @member {String} startTime
 */
RetrieveEdgeStorageServerTask.prototype.startTime = undefined;

/**
 * End time
 * @member {String} endTime
 */
RetrieveEdgeStorageServerTask.prototype.endTime = undefined;

// Implement OneOfinlineResponse20029Result interface:
