/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SetMIPOptionPropertyServerTask model module.
 * @module model/SetMIPOptionPropertyServerTask
 * @version 1.0.0
 */
export class SetMIPOptionPropertyServerTask {
  /**
   * Constructs a new <code>SetMIPOptionPropertyServerTask</code>.
   * Set option menu XML properties
   * @alias module:model/SetMIPOptionPropertyServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SetMIPOptionPropertyServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetMIPOptionPropertyServerTask} obj Optional instance to populate.
   * @return {module:model/SetMIPOptionPropertyServerTask} The populated <code>SetMIPOptionPropertyServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SetMIPOptionPropertyServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('optionId'))
        obj.optionId = ApiClient.convertToType(data['optionId'], 'String');
      if (data.hasOwnProperty('dataVersion'))
        obj.dataVersion = ApiClient.convertToType(data['dataVersion'], 'Number');
      if (data.hasOwnProperty('XML'))
        obj.XML = ApiClient.convertToType(data['XML'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
SetMIPOptionPropertyServerTask.prototype.displayName = undefined;

/**
 * Option ID
 * @member {String} optionId
 */
SetMIPOptionPropertyServerTask.prototype.optionId = undefined;

/**
 * Option data version
 * @member {Number} dataVersion
 */
SetMIPOptionPropertyServerTask.prototype.dataVersion = undefined;

/**
 * Option xml
 * @member {String} XML
 */
SetMIPOptionPropertyServerTask.prototype.XML = undefined;

// Implement OneOfinlineResponse200112Result interface:
