/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CameraPtzChildItem} from './CameraPtzChildItem';
import {SettingsChildItem} from './SettingsChildItem';
import {SettingsRelations} from './SettingsRelations';
import {StreamsChildItem} from './StreamsChildItem';

/**
 * The Settings model module.
 * @module model/Settings
 * @version 1.0.0
 */
export class Settings {
  /**
   * Constructs a new <code>Settings</code>.
   * Settings
   * @alias module:model/Settings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Settings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Settings} obj Optional instance to populate.
   * @return {module:model/Settings} The populated <code>Settings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Settings();
      if (data.hasOwnProperty('settings'))
        obj.settings = SettingsChildItem.constructFromObject(data['settings']);
      if (data.hasOwnProperty('cameraPtz'))
        obj.cameraPtz = CameraPtzChildItem.constructFromObject(data['cameraPtz']);
      if (data.hasOwnProperty('streams'))
        obj.streams = ApiClient.convertToType(data['streams'], [StreamsChildItem]);
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('relations'))
        obj.relations = SettingsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {module:model/SettingsChildItem} settings
 */
Settings.prototype.settings = undefined;

/**
 * @member {module:model/CameraPtzChildItem} cameraPtz
 */
Settings.prototype.cameraPtz = undefined;

/**
 * @member {Array.<module:model/StreamsChildItem>} streams
 */
Settings.prototype.streams = undefined;

/**
 * @member {String} displayName
 */
Settings.prototype.displayName = undefined;

/**
 * @member {module:model/SettingsRelations} relations
 */
Settings.prototype.relations = undefined;

