/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SitesRelations} from './SitesRelations';

/**
 * The Sites model module.
 * @module model/Sites
 * @version 1.0.0
 */
export class Sites {
  /**
   * Constructs a new <code>Sites</code>.
   * Management Server
   * @alias module:model/Sites
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Sites</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Sites} obj Optional instance to populate.
   * @return {module:model/Sites} The populated <code>Sites</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Sites();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('lastModified'))
        obj.lastModified = ApiClient.convertToType(data['lastModified'], 'String');
      if (data.hasOwnProperty('timeZone'))
        obj.timeZone = ApiClient.convertToType(data['timeZone'], 'String');
      if (data.hasOwnProperty('computerName'))
        obj.computerName = ApiClient.convertToType(data['computerName'], 'String');
      if (data.hasOwnProperty('domainName'))
        obj.domainName = ApiClient.convertToType(data['domainName'], 'String');
      if (data.hasOwnProperty('lastStatusHandshake'))
        obj.lastStatusHandshake = ApiClient.convertToType(data['lastStatusHandshake'], 'String');
      if (data.hasOwnProperty('physicalMemory'))
        obj.physicalMemory = ApiClient.convertToType(data['physicalMemory'], 'Number');
      if (data.hasOwnProperty('platform'))
        obj.platform = ApiClient.convertToType(data['platform'], 'String');
      if (data.hasOwnProperty('processors'))
        obj.processors = ApiClient.convertToType(data['processors'], 'Number');
      if (data.hasOwnProperty('serviceAccount'))
        obj.serviceAccount = ApiClient.convertToType(data['serviceAccount'], 'String');
      if (data.hasOwnProperty('synchronizationStatus'))
        obj.synchronizationStatus = ApiClient.convertToType(data['synchronizationStatus'], 'Number');
      if (data.hasOwnProperty('masterSiteAddress'))
        obj.masterSiteAddress = ApiClient.convertToType(data['masterSiteAddress'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('relations'))
        obj.relations = SitesRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
Sites.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
Sites.prototype.id = undefined;

/**
 * Name
 * @member {String} name
 */
Sites.prototype.name = undefined;

/**
 * Description
 * @member {String} description
 */
Sites.prototype.description = undefined;

/**
 * Last modified
 * @member {String} lastModified
 */
Sites.prototype.lastModified = undefined;

/**
 * Time zone
 * @member {String} timeZone
 */
Sites.prototype.timeZone = undefined;

/**
 * Computer name
 * @member {String} computerName
 */
Sites.prototype.computerName = undefined;

/**
 * Domain
 * @member {String} domainName
 */
Sites.prototype.domainName = undefined;

/**
 * Last site status handshake
 * @member {String} lastStatusHandshake
 */
Sites.prototype.lastStatusHandshake = undefined;

/**
 * Physical memory (MB)
 * @member {Number} physicalMemory
 */
Sites.prototype.physicalMemory = undefined;

/**
 * Windows platform
 * @member {String} platform
 */
Sites.prototype.platform = undefined;

/**
 * Processors
 * @member {Number} processors
 */
Sites.prototype.processors = undefined;

/**
 * Management server service account
 * @member {String} serviceAccount
 */
Sites.prototype.serviceAccount = undefined;

/**
 * Site synchronization status
 * @member {Number} synchronizationStatus
 */
Sites.prototype.synchronizationStatus = undefined;

/**
 * Master site url
 * @member {String} masterSiteAddress
 */
Sites.prototype.masterSiteAddress = undefined;

/**
 * Product version
 * @member {String} version
 */
Sites.prototype.version = undefined;

/**
 * @member {module:model/SitesRelations} relations
 */
Sites.prototype.relations = undefined;

