/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Stream} from './Stream';
import {StreamsRelations} from './StreamsRelations';

/**
 * The Streams model module.
 * @module model/Streams
 * @version 1.0.0
 */
export class Streams {
  /**
   * Constructs a new <code>Streams</code>.
   * Stream
   * @alias module:model/Streams
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Streams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Streams} obj Optional instance to populate.
   * @return {module:model/Streams} The populated <code>Streams</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Streams();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('stream'))
        obj.stream = ApiClient.convertToType(data['stream'], [Stream]);
      if (data.hasOwnProperty('relations'))
        obj.relations = StreamsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
Streams.prototype.displayName = undefined;

/**
 * @member {Array.<module:model/Stream>} stream
 */
Streams.prototype.stream = undefined;

/**
 * @member {module:model/StreamsRelations} relations
 */
Streams.prototype.relations = undefined;

