/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TasksResult model module.
 * @module model/TasksResult
 * @version 1.0.0
 */
export class TasksResult {
  /**
   * Constructs a new <code>TasksResult</code>.
   * @alias module:model/TasksResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TasksResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TasksResult} obj Optional instance to populate.
   * @return {module:model/TasksResult} The populated <code>TasksResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TasksResult();
      if (data.hasOwnProperty('progress'))
        obj.progress = ApiClient.convertToType(data['progress'], 'Number');
      if (data.hasOwnProperty('errorCode'))
        obj.errorCode = ApiClient.convertToType(data['errorCode'], 'Number');
      if (data.hasOwnProperty('errorText'))
        obj.errorText = ApiClient.convertToType(data['errorText'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} progress
 */
TasksResult.prototype.progress = undefined;

/**
 * @member {Number} errorCode
 */
TasksResult.prototype.errorCode = undefined;

/**
 * @member {String} errorText
 */
TasksResult.prototype.errorText = undefined;

/**
 * @member {String} state
 */
TasksResult.prototype.state = undefined;

/**
 * @member {String} path
 */
TasksResult.prototype.path = undefined;

