/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Translations model module.
 * @module model/Translations
 * @version 1.0.0
 */
export class Translations {
  /**
   * Constructs a new <code>Translations</code>.
   * @alias module:model/Translations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Translations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Translations} obj Optional instance to populate.
   * @return {module:model/Translations} The populated <code>Translations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Translations();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Translations.prototype.id = undefined;

/**
 * @member {String} text
 */
Translations.prototype.text = undefined;

