/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UploadFileChunkServerTask model module.
 * @module model/UploadFileChunkServerTask
 * @version 1.0.0
 */
export class UploadFileChunkServerTask {
  /**
   * Constructs a new <code>UploadFileChunkServerTask</code>.
   * Upload file chunk
   * @alias module:model/UploadFileChunkServerTask
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UploadFileChunkServerTask</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UploadFileChunkServerTask} obj Optional instance to populate.
   * @return {module:model/UploadFileChunkServerTask} The populated <code>UploadFileChunkServerTask</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UploadFileChunkServerTask();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('transferId'))
        obj.transferId = ApiClient.convertToType(data['transferId'], 'String');
      if (data.hasOwnProperty('chunkData'))
        obj.chunkData = ApiClient.convertToType(data['chunkData'], 'String');
      if (data.hasOwnProperty('offset'))
        obj.offset = ApiClient.convertToType(data['offset'], 'Number');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'Number');
      if (data.hasOwnProperty('checksum'))
        obj.checksum = ApiClient.convertToType(data['checksum'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
UploadFileChunkServerTask.prototype.displayName = undefined;

/**
 * Transfer ID. The transfer ID used to identify the file transfer
 * @member {String} transferId
 */
UploadFileChunkServerTask.prototype.transferId = undefined;

/**
 * Chunk data. The chunk data as a base64 encoded string
 * @member {String} chunkData
 */
UploadFileChunkServerTask.prototype.chunkData = undefined;

/**
 * Offset (bytes). The chunk offset in bytes
 * @member {Number} offset
 */
UploadFileChunkServerTask.prototype.offset = undefined;

/**
 * File size (bytes). The total file size in bytes
 * @member {Number} size
 */
UploadFileChunkServerTask.prototype.size = undefined;

/**
 * Checksum. The checksum as a base64 encoded string
 * @member {String} checksum
 */
UploadFileChunkServerTask.prototype.checksum = undefined;

// Implement OneOfinlineResponse200163Result interface:
