/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VideoWallsRelations} from './VideoWallsRelations';

/**
 * The VideoWalls model module.
 * @module model/VideoWalls
 * @version 1.0.0
 */
export class VideoWalls {
  /**
   * Constructs a new <code>VideoWalls</code>.
   * Video wall
   * @alias module:model/VideoWalls
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>VideoWalls</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VideoWalls} obj Optional instance to populate.
   * @return {module:model/VideoWalls} The populated <code>VideoWalls</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VideoWalls();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('lastModified'))
        obj.lastModified = ApiClient.convertToType(data['lastModified'], 'String');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'String');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('statusText'))
        obj.statusText = ApiClient.convertToType(data['statusText'], 'Boolean');
      if (data.hasOwnProperty('titleBar'))
        obj.titleBar = ApiClient.convertToType(data['titleBar'], 'String');
      if (data.hasOwnProperty('relations'))
        obj.relations = VideoWallsRelations.constructFromObject(data['relations']);
    }
    return obj;
  }
}

/**
 * @member {String} displayName
 */
VideoWalls.prototype.displayName = undefined;

/**
 * ID
 * @member {String} id
 */
VideoWalls.prototype.id = undefined;

/**
 * Name
 * @member {String} name
 */
VideoWalls.prototype.name = undefined;

/**
 * Description
 * @member {String} description
 */
VideoWalls.prototype.description = undefined;

/**
 * Last modified
 * @member {String} lastModified
 */
VideoWalls.prototype.lastModified = undefined;

/**
 * Created date
 * @member {String} createdDate
 */
VideoWalls.prototype.createdDate = undefined;

/**
 * Height
 * @member {Number} height
 */
VideoWalls.prototype.height = undefined;

/**
 * Status text. Is status text shown
 * @member {Boolean} statusText
 */
VideoWalls.prototype.statusText = undefined;

/**
 * Allowed values for the <code>titleBar</code> property.
 * @enum {String}
 * @readonly
 */
VideoWalls.TitleBarEnum = {
  /**
   * value: "None"
   * @const
   */
  none: "None",

  /**
   * value: "Caption"
   * @const
   */
  caption: "Caption"
};
/**
 * Title bar. What to show in the title bar. Value map to display names:  None=None   Caption=Caption   
 * @member {module:model/VideoWalls.TitleBarEnum} titleBar
 */
VideoWalls.prototype.titleBar = undefined;

/**
 * @member {module:model/VideoWallsRelations} relations
 */
VideoWalls.prototype.relations = undefined;

